### ISSUE TITLE
Redirect on formsubmit

### ISSUE THREAD

**Issue by melcarthus** [GawainLynch/bolt-extension-boltforms#34]
This is my form in the .yml file.

```yammel

# Commentsform
comments:
  feedback:
    redirect:
      target: http://www.make-itjustforyou.nl/reviews
  templates:
    form: boltforms_form_comments.twig
  database:
    contenttype: comments
  fields:
    record_type:
      type: hidden
    record_id:
      type: hidden
    title:
      type: text
      options:
        required: true
        label: Uw naam
    comment:
      type: textarea
      options:
        required: true
        label: Schrijf een review
        attr:
          placeholder: Your message...
          class: cf-comment
    submit:
      type: submit

```

I have also tried /page/reviews and page/reviews and reviews as target. But the form wil not redirect.

I build a comment form off another post. Which is working fine btw, the only thing I can't figure out is why on submit the form wont redirect to the same page. I want to do this because I don't want users to F5 and resubmit there comment again. If there is any other way to prevent this I would like to be pointed in to the right direction. I'm really starting to get the hang of Bolt, So i'm not looking for a copy paste sollution unless its stupid easy facepalming obvious, and I just overlooked something
https://github.com/bolt/bolt/issues/3472

**Comment by GawainLynch** [comment]
I have just published v2.2.0 of BoltForms, (that now includes full unit testing). Can you give that a try?

Someone else on IRC had mentioned a problem with this as well, but I made a few changes to the code and tested it here prior to tagging the release and it all works. :+1:

**Comment by melcarthus** [comment]
I will..., How come the update leaves the config file as is but deletes my custom form twig i used for the comment section? I have to restore a backup and get back to you is the redirect is working in my custom form.

**Comment by melcarthus** [comment]
Ok, everything is back to normal. Is there anyway that I can change the location of my own boltform twig file so that it does not get deleted with an update?

Anyway... If I did the redirect correctly I have to assume it is still not working. I changed the target to pages/reviews. But whenever someone sets a wrong path or url it should go to the 404 page no?

**Comment by GawainLynch** [comment]
Composer [treats the `vendor/` directories as volatile](https://igor.io/2013/09/04/composer-vendor-directory.html)… If you want to use custom Twig templates, the best place for them is in your theme directory. 

I usually just create `theme/mytheme/extensions/boltforms/my-custom-file.twig` and do it that way, then in the BoltForms config:

```yaml
  templates:
    form: extensions/boltforms/my-custom-file.twig
```

**Comment by GawainLynch** [comment]
> But whenever someone sets a wrong path or url it should go to the 404 page no?

With paths, it checks if the [record exists](https://github.com/GawainLynch/bolt-extension-boltforms/blob/master/src/BoltForms.php#L454-L456) which I think just make me click on to what you and @evertalbers are seeing… The original feature request was for records, not listings… This is what I refer to as the Samuel L. Jackson Assumption Rule.

Give me a bit of time and I will do an update to handle valid Bolt routes in general! :grin:

**Comment by melcarthus** [comment]
Thx for the quicktip, learned another awesome thing today. I'll wait, i'll just set the comments to not published so the client can add them manually in case of double / triple or in some user cases quadruple submits :smile:

**Comment by GawainLynch** [comment]
> Thx for the quicktip, learned another awesome thing today

Yeah, Twig gets better and better the more you master it… I am a backend person so still very much learning myself and enjoying that same feeling :grin: 

I shouldn't be too long with an update… It's a choice between this and CI test infrastructure bugs… This wins hands down!

**Comment by melcarthus** [comment]
With this fix is coming I could ask no more from bolt forms. IMHO everything needs to stay as basic as possible, en use extensions for extra functions, just like bolt took out the comment section from pivot.

Now that this comment section is working thx to the issue I linked earlier I can finally say goodbye to wordpress and drupal!

Closing time! :sweat_smile:

**Comment by GawainLynch** [comment]
OK, sorry for the delay… it was an easy fix, but my lovely wife wanted to have some lunch with me… and even being Australian you can't escape Portuguese lunch culture.

Anyway… we now only will fail to redirect if the target either; a) doesn't start with `http://` or `https://`; or b) isn't a *valid* site route.

Please let me know if that *now* works for you.

**Side note**: v2.2.1 might not appear on the install list for another hour

**Comment by melcarthus** [comment]
Well I saw this comment just a couple of minutes ago, and thus it has been more then an hour and it was in the install list :smile: 

Happy to tell you it works! I've set the route to page/reviews and voila!

Thx mate :smiley:

**Comment by GawainLynch** [comment]
Yay! Thanks for the constructive feedback… I am sure there are a couple of people that will be happy with this outcome :grin:

**Comment by melcarthus** [comment]
No problem! Alsways trying to think of others in a community :sunglasses:

**Comment by niranjanpawar7** [comment]
hello in bolt i have developed my website successfully... now am not able to understand how to intrgrate form with content types and page with database....please find below code and help me out please

<form  method="post" id="rightform">
               <div class="form-group col-md-12 nopadding">
                  <input type="text" name="name" class="form-control"  placeholder="Name">
               </div>
               <div class="form-group col-md-12 nopadding">
                  <input type="email" name="email" class="form-control" placeholder="Email">
               </div>
               <div class="form-group col-md-12 nopadding">
                  <input class="form-control" type="tel" maxlength="10" pattern="^\d{4}\d{3}\d{3}$" onkeypress="return isNumber(event)" name="contact" placeholder="Phone">
               </div>
               <div class="form-group col-md-12 nopadding">
                  <input type="text" name="comment" class="form-control"  placeholder="Comments">
               </div>
               <input type="hidden" name="medium" value="quote" />
               <center>
                  <button type="submit" class="btn btn-default">Submit</button>
               </center>
               <div class="clearfix" style="height:10px"></div>
            </form>
